motd=MineTuff | 100-World Mining Network
online-mode=true
enforce-secure-profile=true
max-players=10000
view-distance=6
simulation-distance=4
spawn-protection=0
allow-flight=false
allow-nether=false
generate-structures=false
difficulty=peaceful
pvp=false
sync-chunk-writes=false
network-compression-threshold=512
use-native-transport=true
enable-query=false
enable-rcon=false
